### PR TITLE
En6 6

### PR DESCRIPTION
**Pull request by ampie**

### CODE REVIEW

**Comment by ampie** [comment]
[0% (0.0%) vs master 0%](https://jenkins.entandocloud.com/job/entando-config-service-pr/3/)

**Comment by entando-service** [comment]
All is well

**Comment by ampie** [comment]
[98% (0.0%) vs master 98%](https://jenkins.entandocloud.com/job/entando-config-service-pr/5/)

**Comment by entando-service** [comment]
All is well

**Comment by ampie** [comment]
Try again please

**Comment by entando-service** [comment]
All is well

**Pull request closed without merging**
